package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallAllianceSale;
import org.linlinjava.litemall.db.domain.LitemallAllianceSaleExample;

public interface LitemallAllianceSaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    long countByExample(LitemallAllianceSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAllianceSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    int insert(LitemallAllianceSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAllianceSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    LitemallAllianceSale selectOneByExample(LitemallAllianceSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    LitemallAllianceSale selectOneByExampleSelective(@Param("example") LitemallAllianceSaleExample example, @Param("selective") LitemallAllianceSale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    List<LitemallAllianceSale> selectByExampleSelective(@Param("example") LitemallAllianceSaleExample example, @Param("selective") LitemallAllianceSale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    List<LitemallAllianceSale> selectByExample(LitemallAllianceSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    LitemallAllianceSale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAllianceSale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    LitemallAllianceSale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAllianceSale record, @Param("example") LitemallAllianceSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAllianceSale record, @Param("example") LitemallAllianceSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAllianceSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAllianceSale record);
}