package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallActivity;
import org.linlinjava.litemall.db.domain.LitemallActivityExample;

public interface LitemallActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    long countByExample(LitemallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    int insert(LitemallActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    int insertSelective(LitemallActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    LitemallActivity selectOneByExample(LitemallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    LitemallActivity selectOneByExampleSelective(@Param("example") LitemallActivityExample example, @Param("selective") LitemallActivity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    List<LitemallActivity> selectByExampleSelective(@Param("example") LitemallActivityExample example, @Param("selective") LitemallActivity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    List<LitemallActivity> selectByExample(LitemallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    LitemallActivity selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallActivity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    LitemallActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    LitemallActivity selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallActivity record, @Param("example") LitemallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallActivity record, @Param("example") LitemallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_activity
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}