package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallStockRecord;
import org.linlinjava.litemall.db.domain.LitemallStockRecordExample;

public interface LitemallStockRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    long countByExample(LitemallStockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallStockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    int insert(LitemallStockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    int insertSelective(LitemallStockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    LitemallStockRecord selectOneByExample(LitemallStockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    LitemallStockRecord selectOneByExampleSelective(@Param("example") LitemallStockRecordExample example, @Param("selective") LitemallStockRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    List<LitemallStockRecord> selectByExampleSelective(@Param("example") LitemallStockRecordExample example, @Param("selective") LitemallStockRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    List<LitemallStockRecord> selectByExample(LitemallStockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    LitemallStockRecord selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallStockRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    LitemallStockRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallStockRecord record, @Param("example") LitemallStockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallStockRecord record, @Param("example") LitemallStockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallStockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallStockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallStockRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_stock_record
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallStockRecord> list, @Param("selective") LitemallStockRecord.Column ... selective);
}