package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPlant;
import org.linlinjava.litemall.db.domain.LitemallPlantExample;

public interface LitemallPlantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    long countByExample(LitemallPlantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPlantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    int insert(LitemallPlant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPlant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    LitemallPlant selectOneByExample(LitemallPlantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    LitemallPlant selectOneByExampleSelective(@Param("example") LitemallPlantExample example, @Param("selective") LitemallPlant.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    List<LitemallPlant> selectByExampleSelective(@Param("example") LitemallPlantExample example, @Param("selective") LitemallPlant.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    List<LitemallPlant> selectByExample(LitemallPlantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    LitemallPlant selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPlant.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    LitemallPlant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    LitemallPlant selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPlant record, @Param("example") LitemallPlantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPlant record, @Param("example") LitemallPlantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPlant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPlant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallPlantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_plant
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    List<LitemallPlant> sel(@Param("name") String name, @Param("phone") String phone, @Param("contacts") String contacts, @Param("addTime") String addTime);

    LitemallPlant findById(@Param("id") Integer id);
}
