package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallAlliance;
import org.linlinjava.litemall.db.domain.LitemallAllianceExample;


public interface LitemallAllianceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    long countByExample(LitemallAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    int insert(LitemallAlliance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAlliance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    LitemallAlliance selectOneByExample(LitemallAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    LitemallAlliance selectOneByExampleSelective(@Param("example") LitemallAllianceExample example, @Param("selective") LitemallAlliance.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    List<LitemallAlliance> selectByExampleSelective(@Param("example") LitemallAllianceExample example, @Param("selective") LitemallAlliance.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    List<LitemallAlliance> selectByExample(LitemallAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    LitemallAlliance selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAlliance.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    LitemallAlliance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    LitemallAlliance selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAlliance record, @Param("example") LitemallAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAlliance record, @Param("example") LitemallAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAlliance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAlliance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_alliance
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    LitemallAlliance selByUserId(@Param("id") Integer id);

    void delByUserId(@Param("id") Integer id);

    LitemallAlliance selByAddress(@Param("address") String address);
}
