package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallProductFactory;
import org.linlinjava.litemall.db.domain.LitemallProductFactoryExample;

public interface LitemallProductFactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    long countByExample(LitemallProductFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallProductFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    int insert(LitemallProductFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    int insertSelective(LitemallProductFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    LitemallProductFactory selectOneByExample(LitemallProductFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    LitemallProductFactory selectOneByExampleSelective(@Param("example") LitemallProductFactoryExample example, @Param("selective") LitemallProductFactory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    List<LitemallProductFactory> selectByExampleSelective(@Param("example") LitemallProductFactoryExample example, @Param("selective") LitemallProductFactory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    List<LitemallProductFactory> selectByExample(LitemallProductFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    LitemallProductFactory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallProductFactory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    LitemallProductFactory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallProductFactory record, @Param("example") LitemallProductFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallProductFactory record, @Param("example") LitemallProductFactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallProductFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallProductFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallProductFactory> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_product_factory
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallProductFactory> list, @Param("selective") LitemallProductFactory.Column ... selective);

    String selInventory(@Param("goodsCodeId") Integer goodsCodeId);

    LitemallProductFactory getOneByGoodId(@Param("goodsCodeId") Integer goodsCodeId, @Param("specCodeId") Integer specCodeId);

    int reduceStock(@Param("id") Integer id, @Param("num") Short num);

    int addStock(@Param("goodsCodeId") Integer goodsCodeId, @Param("specCodeId") Integer specCodeId, @Param("plantId") Integer plantId, @Param("num") Short num);

}