package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSpecodeProduct;
import org.linlinjava.litemall.db.domain.LitemallSpecodeProductExample;

public interface LitemallSpecodeProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    long countByExample(LitemallSpecodeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSpecodeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    int insert(LitemallSpecodeProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSpecodeProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    LitemallSpecodeProduct selectOneByExample(LitemallSpecodeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    LitemallSpecodeProduct selectOneByExampleSelective(@Param("example") LitemallSpecodeProductExample example, @Param("selective") LitemallSpecodeProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    List<LitemallSpecodeProduct> selectByExampleSelective(@Param("example") LitemallSpecodeProductExample example, @Param("selective") LitemallSpecodeProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    List<LitemallSpecodeProduct> selectByExample(LitemallSpecodeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    LitemallSpecodeProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSpecodeProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    LitemallSpecodeProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSpecodeProduct record, @Param("example") LitemallSpecodeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSpecodeProduct record, @Param("example") LitemallSpecodeProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSpecodeProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSpecodeProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallSpecodeProduct> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_specode_product
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallSpecodeProduct> list, @Param("selective") LitemallSpecodeProduct.Column ... selective);

    int addStock(@Param("goodsCodeId") Integer goodsCodeId, @Param("specCodeId") Integer specCodeId, @Param("num") Short num);

}
