package org.linlinjava.litemall.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallNodeRelation;
import org.linlinjava.litemall.db.domain.LitemallNodeRelationExample;

public interface LitemallNodeRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    long countByExample(LitemallNodeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallNodeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    int insert(LitemallNodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    int insertSelective(LitemallNodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    LitemallNodeRelation selectOneByExample(LitemallNodeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    LitemallNodeRelation selectOneByExampleSelective(@Param("example") LitemallNodeRelationExample example, @Param("selective") LitemallNodeRelation.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    List<LitemallNodeRelation> selectByExampleSelective(@Param("example") LitemallNodeRelationExample example, @Param("selective") LitemallNodeRelation.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    List<LitemallNodeRelation> selectByExample(LitemallNodeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    LitemallNodeRelation selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallNodeRelation.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    LitemallNodeRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallNodeRelation record, @Param("example") LitemallNodeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallNodeRelation record, @Param("example") LitemallNodeRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallNodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_node_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallNodeRelation record);

}
