package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsSpec;
import org.linlinjava.litemall.db.domain.LitemallGoodsSpecExample;

public interface LitemallGoodsSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    LitemallGoodsSpec selectOneByExample(LitemallGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    LitemallGoodsSpec selectOneByExampleSelective(@Param("example") LitemallGoodsSpecExample example, @Param("selective") LitemallGoodsSpec.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    List<LitemallGoodsSpec> selectByExampleSelective(@Param("example") LitemallGoodsSpecExample example, @Param("selective") LitemallGoodsSpec.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    List<LitemallGoodsSpec> selectByExample(LitemallGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    LitemallGoodsSpec selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsSpec.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    LitemallGoodsSpec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsSpec record, @Param("example") LitemallGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsSpec record, @Param("example") LitemallGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallGoodsSpec> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_spec
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallGoodsSpec> list, @Param("selective") LitemallGoodsSpec.Column ... selective);
}