package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsCode;
import org.linlinjava.litemall.db.domain.LitemallGoodsCodeExample;

public interface LitemallGoodsCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    LitemallGoodsCode selectOneByExample(LitemallGoodsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    LitemallGoodsCode selectOneByExampleSelective(@Param("example") LitemallGoodsCodeExample example, @Param("selective") LitemallGoodsCode.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    List<LitemallGoodsCode> selectByExampleSelective(@Param("example") LitemallGoodsCodeExample example, @Param("selective") LitemallGoodsCode.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    List<LitemallGoodsCode> selectByExample(LitemallGoodsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    LitemallGoodsCode selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsCode.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    LitemallGoodsCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsCode record, @Param("example") LitemallGoodsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsCode record, @Param("example") LitemallGoodsCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsCode record);
}