package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallAftersale {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_aftersale
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_aftersale
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.aftersale_sn
     *
     * @mbg.generated
     */
    private String aftersaleSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.plant_id
     *
     * @mbg.generated
     */
    private Integer plantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.order_goods_id
     *
     * @mbg.generated
     */
    private Integer orderGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.service_type
     *
     * @mbg.generated
     */
    private Integer serviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.cargo_status
     *
     * @mbg.generated
     */
    private Integer cargoStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.pictures
     *
     * @mbg.generated
     */
    private String[] pictures;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.courier_number
     *
     * @mbg.generated
     */
    private String courierNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.courier_company
     *
     * @mbg.generated
     */
    private String courierCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.reject_reason
     *
     * @mbg.generated
     */
    private String rejectReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.handle_time
     *
     * @mbg.generated
     */
    private LocalDateTime handleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.pay_id
     *
     * @mbg.generated
     */
    private String payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.last_operator
     *
     * @mbg.generated
     */
    private Integer lastOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.refund_id
     *
     * @mbg.generated
     */
    private String refundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_aftersale.confirm_return
     *
     * @mbg.generated
     */
    private Boolean confirmReturn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.id
     *
     * @return the value of litemall_aftersale.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.id
     *
     * @param id the value for litemall_aftersale.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.user_id
     *
     * @return the value of litemall_aftersale.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.user_id
     *
     * @param userId the value for litemall_aftersale.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.aftersale_sn
     *
     * @return the value of litemall_aftersale.aftersale_sn
     *
     * @mbg.generated
     */
    public String getAftersaleSn() {
        return aftersaleSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.aftersale_sn
     *
     * @param aftersaleSn the value for litemall_aftersale.aftersale_sn
     *
     * @mbg.generated
     */
    public void setAftersaleSn(String aftersaleSn) {
        this.aftersaleSn = aftersaleSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.order_id
     *
     * @return the value of litemall_aftersale.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.order_id
     *
     * @param orderId the value for litemall_aftersale.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.plant_id
     *
     * @return the value of litemall_aftersale.plant_id
     *
     * @mbg.generated
     */
    public Integer getPlantId() {
        return plantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.plant_id
     *
     * @param plantId the value for litemall_aftersale.plant_id
     *
     * @mbg.generated
     */
    public void setPlantId(Integer plantId) {
        this.plantId = plantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.order_goods_id
     *
     * @return the value of litemall_aftersale.order_goods_id
     *
     * @mbg.generated
     */
    public Integer getOrderGoodsId() {
        return orderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.order_goods_id
     *
     * @param orderGoodsId the value for litemall_aftersale.order_goods_id
     *
     * @mbg.generated
     */
    public void setOrderGoodsId(Integer orderGoodsId) {
        this.orderGoodsId = orderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.service_type
     *
     * @return the value of litemall_aftersale.service_type
     *
     * @mbg.generated
     */
    public Integer getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.service_type
     *
     * @param serviceType the value for litemall_aftersale.service_type
     *
     * @mbg.generated
     */
    public void setServiceType(Integer serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.cargo_status
     *
     * @return the value of litemall_aftersale.cargo_status
     *
     * @mbg.generated
     */
    public Integer getCargoStatus() {
        return cargoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.cargo_status
     *
     * @param cargoStatus the value for litemall_aftersale.cargo_status
     *
     * @mbg.generated
     */
    public void setCargoStatus(Integer cargoStatus) {
        this.cargoStatus = cargoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.reason
     *
     * @return the value of litemall_aftersale.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.reason
     *
     * @param reason the value for litemall_aftersale.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.amount
     *
     * @return the value of litemall_aftersale.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.amount
     *
     * @param amount the value for litemall_aftersale.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.pictures
     *
     * @return the value of litemall_aftersale.pictures
     *
     * @mbg.generated
     */
    public String[] getPictures() {
        return pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.pictures
     *
     * @param pictures the value for litemall_aftersale.pictures
     *
     * @mbg.generated
     */
    public void setPictures(String[] pictures) {
        this.pictures = pictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.comment
     *
     * @return the value of litemall_aftersale.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.comment
     *
     * @param comment the value for litemall_aftersale.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.courier_number
     *
     * @return the value of litemall_aftersale.courier_number
     *
     * @mbg.generated
     */
    public String getCourierNumber() {
        return courierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.courier_number
     *
     * @param courierNumber the value for litemall_aftersale.courier_number
     *
     * @mbg.generated
     */
    public void setCourierNumber(String courierNumber) {
        this.courierNumber = courierNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.courier_company
     *
     * @return the value of litemall_aftersale.courier_company
     *
     * @mbg.generated
     */
    public String getCourierCompany() {
        return courierCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.courier_company
     *
     * @param courierCompany the value for litemall_aftersale.courier_company
     *
     * @mbg.generated
     */
    public void setCourierCompany(String courierCompany) {
        this.courierCompany = courierCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.status
     *
     * @return the value of litemall_aftersale.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.status
     *
     * @param status the value for litemall_aftersale.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.reject_reason
     *
     * @return the value of litemall_aftersale.reject_reason
     *
     * @mbg.generated
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.reject_reason
     *
     * @param rejectReason the value for litemall_aftersale.reject_reason
     *
     * @mbg.generated
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.handle_time
     *
     * @return the value of litemall_aftersale.handle_time
     *
     * @mbg.generated
     */
    public LocalDateTime getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.handle_time
     *
     * @param handleTime the value for litemall_aftersale.handle_time
     *
     * @mbg.generated
     */
    public void setHandleTime(LocalDateTime handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.add_time
     *
     * @return the value of litemall_aftersale.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.add_time
     *
     * @param addTime the value for litemall_aftersale.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.update_time
     *
     * @return the value of litemall_aftersale.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.update_time
     *
     * @param updateTime the value for litemall_aftersale.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_aftersale
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.deleted
     *
     * @return the value of litemall_aftersale.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.deleted
     *
     * @param deleted the value for litemall_aftersale.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.pay_id
     *
     * @return the value of litemall_aftersale.pay_id
     *
     * @mbg.generated
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.pay_id
     *
     * @param payId the value for litemall_aftersale.pay_id
     *
     * @mbg.generated
     */
    public void setPayId(String payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.last_operator
     *
     * @return the value of litemall_aftersale.last_operator
     *
     * @mbg.generated
     */
    public Integer getLastOperator() {
        return lastOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.last_operator
     *
     * @param lastOperator the value for litemall_aftersale.last_operator
     *
     * @mbg.generated
     */
    public void setLastOperator(Integer lastOperator) {
        this.lastOperator = lastOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.refund_id
     *
     * @return the value of litemall_aftersale.refund_id
     *
     * @mbg.generated
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.refund_id
     *
     * @param refundId the value for litemall_aftersale.refund_id
     *
     * @mbg.generated
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_aftersale.confirm_return
     *
     * @return the value of litemall_aftersale.confirm_return
     *
     * @mbg.generated
     */
    public Boolean getConfirmReturn() {
        return confirmReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_aftersale.confirm_return
     *
     * @param confirmReturn the value for litemall_aftersale.confirm_return
     *
     * @mbg.generated
     */
    public void setConfirmReturn(Boolean confirmReturn) {
        this.confirmReturn = confirmReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_aftersale
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", aftersaleSn=").append(aftersaleSn);
        sb.append(", orderId=").append(orderId);
        sb.append(", plantId=").append(plantId);
        sb.append(", orderGoodsId=").append(orderGoodsId);
        sb.append(", serviceType=").append(serviceType);
        sb.append(", cargoStatus=").append(cargoStatus);
        sb.append(", reason=").append(reason);
        sb.append(", amount=").append(amount);
        sb.append(", pictures=").append(pictures);
        sb.append(", comment=").append(comment);
        sb.append(", courierNumber=").append(courierNumber);
        sb.append(", courierCompany=").append(courierCompany);
        sb.append(", status=").append(status);
        sb.append(", rejectReason=").append(rejectReason);
        sb.append(", handleTime=").append(handleTime);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", payId=").append(payId);
        sb.append(", lastOperator=").append(lastOperator);
        sb.append(", refundId=").append(refundId);
        sb.append(", confirmReturn=").append(confirmReturn);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_aftersale
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallAftersale other = (LitemallAftersale) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAftersaleSn() == null ? other.getAftersaleSn() == null : this.getAftersaleSn().equals(other.getAftersaleSn()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getPlantId() == null ? other.getPlantId() == null : this.getPlantId().equals(other.getPlantId()))
            && (this.getOrderGoodsId() == null ? other.getOrderGoodsId() == null : this.getOrderGoodsId().equals(other.getOrderGoodsId()))
            && (this.getServiceType() == null ? other.getServiceType() == null : this.getServiceType().equals(other.getServiceType()))
            && (this.getCargoStatus() == null ? other.getCargoStatus() == null : this.getCargoStatus().equals(other.getCargoStatus()))
            && (this.getReason() == null ? other.getReason() == null : this.getReason().equals(other.getReason()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (Arrays.equals(this.getPictures(), other.getPictures()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getCourierNumber() == null ? other.getCourierNumber() == null : this.getCourierNumber().equals(other.getCourierNumber()))
            && (this.getCourierCompany() == null ? other.getCourierCompany() == null : this.getCourierCompany().equals(other.getCourierCompany()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRejectReason() == null ? other.getRejectReason() == null : this.getRejectReason().equals(other.getRejectReason()))
            && (this.getHandleTime() == null ? other.getHandleTime() == null : this.getHandleTime().equals(other.getHandleTime()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getPayId() == null ? other.getPayId() == null : this.getPayId().equals(other.getPayId()))
            && (this.getLastOperator() == null ? other.getLastOperator() == null : this.getLastOperator().equals(other.getLastOperator()))
            && (this.getRefundId() == null ? other.getRefundId() == null : this.getRefundId().equals(other.getRefundId()))
            && (this.getConfirmReturn() == null ? other.getConfirmReturn() == null : this.getConfirmReturn().equals(other.getConfirmReturn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_aftersale
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAftersaleSn() == null) ? 0 : getAftersaleSn().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getPlantId() == null) ? 0 : getPlantId().hashCode());
        result = prime * result + ((getOrderGoodsId() == null) ? 0 : getOrderGoodsId().hashCode());
        result = prime * result + ((getServiceType() == null) ? 0 : getServiceType().hashCode());
        result = prime * result + ((getCargoStatus() == null) ? 0 : getCargoStatus().hashCode());
        result = prime * result + ((getReason() == null) ? 0 : getReason().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + (Arrays.hashCode(getPictures()));
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getCourierNumber() == null) ? 0 : getCourierNumber().hashCode());
        result = prime * result + ((getCourierCompany() == null) ? 0 : getCourierCompany().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRejectReason() == null) ? 0 : getRejectReason().hashCode());
        result = prime * result + ((getHandleTime() == null) ? 0 : getHandleTime().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getPayId() == null) ? 0 : getPayId().hashCode());
        result = prime * result + ((getLastOperator() == null) ? 0 : getLastOperator().hashCode());
        result = prime * result + ((getRefundId() == null) ? 0 : getRefundId().hashCode());
        result = prime * result + ((getConfirmReturn() == null) ? 0 : getConfirmReturn().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_aftersale
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_aftersale
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        aftersaleSn("aftersale_sn", "aftersaleSn", "VARCHAR", false),
        orderId("order_id", "orderId", "INTEGER", false),
        plantId("plant_id", "plantId", "INTEGER", false),
        orderGoodsId("order_goods_id", "orderGoodsId", "INTEGER", false),
        serviceType("service_type", "serviceType", "INTEGER", false),
        cargoStatus("cargo_status", "cargoStatus", "INTEGER", false),
        reason("reason", "reason", "VARCHAR", false),
        amount("amount", "amount", "DECIMAL", false),
        pictures("pictures", "pictures", "VARCHAR", false),
        comment("comment", "comment", "VARCHAR", true),
        courierNumber("courier_number", "courierNumber", "VARCHAR", false),
        courierCompany("courier_company", "courierCompany", "VARCHAR", false),
        status("status", "status", "INTEGER", true),
        rejectReason("reject_reason", "rejectReason", "VARCHAR", false),
        handleTime("handle_time", "handleTime", "TIMESTAMP", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        payId("pay_id", "payId", "VARCHAR", false),
        lastOperator("last_operator", "lastOperator", "INTEGER", false),
        refundId("refund_id", "refundId", "VARCHAR", false),
        confirmReturn("confirm_return", "confirmReturn", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_aftersale
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}